package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/_GestionUsuariosStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, March 5, 2022 10:59:07 AM COT
*/

public class _GestionUsuariosStub extends org.omg.CORBA.portable.ObjectImpl implements s_gestion_usuarios.sop_corba.GestionUsuarios
{

  public int abrirSesion (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.CredencialesDTO credenciales)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("abrirSesion", true);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.CredencialesDTOHelper.write ($out, credenciales);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return abrirSesion (credenciales        );
            } finally {
                _releaseReply ($in);
            }
  } // abrirSesion

  public boolean registrarPersonal (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO personal)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarPersonal", true);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.write ($out, personal);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarPersonal (personal        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarPersonal

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO consultarPersonal (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarPersonal", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO $result = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarPersonal (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarPersonal

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO[] listarPersonal ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarPersonal", true);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO $result[] = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonasHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarPersonal (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarPersonal

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO modificarPersonal (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO personal)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modificarPersonal", true);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.write ($out, personal);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO $result = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return modificarPersonal (personal        );
            } finally {
                _releaseReply ($in);
            }
  } // modificarPersonal

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO eliminarPersonal (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarPersonal", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO $result = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarPersonal (id        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarPersonal

  public boolean registrarPaciente (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO paciente)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarPaciente", true);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.write ($out, paciente);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarPaciente (paciente        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarPaciente

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO consultarPaciente (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarPaciente", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO $result = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarPaciente (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarPaciente

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO[] listarPacientes ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarPacientes", true);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO $result[] = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacientesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarPacientes (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarPacientes

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO modificarPaciente (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO paciente)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modificarPaciente", true);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.write ($out, paciente);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO $result = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return modificarPaciente (paciente        );
            } finally {
                _releaseReply ($in);
            }
  } // modificarPaciente

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO eliminarPaciente (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarPaciente", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO $result = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarPaciente (id        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarPaciente

  public boolean registrarValoracionFisica (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTO valoracion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarValoracionFisica", true);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTOHelper.write ($out, valoracion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarValoracionFisica (valoracion        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarValoracionFisica

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTO consultarValoracionFisica (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarValoracionFisica", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTO $result = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarValoracionFisica (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarValoracionFisica

  public boolean registrarAsistencia (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTO asistencia)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarAsistencia", true);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTOHelper.write ($out, asistencia);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarAsistencia (asistencia        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarAsistencia

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTO[] consultarAsistencia (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarAsistencia", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTO $result[] = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciasHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarAsistencia (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarAsistencia

  public boolean registrarProgramaFisico (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO programa)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarProgramaFisico", true);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTOHelper.write ($out, programa);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarProgramaFisico (programa        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarProgramaFisico

  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO consultarProgramaFisico (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarProgramaFisico", true);
                $out.write_long (id);
                $in = _invoke ($out);
                s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO $result = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarProgramaFisico (id        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarProgramaFisico

  public void registrarCallback (s_gestion_usuarios.sop_corba.PafCallback callback)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarCallback", true);
                s_gestion_usuarios.sop_corba.PafCallbackHelper.write ($out, callback);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarCallback (callback        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarCallback

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionUsuarios:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionUsuariosStub
