package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionUsuariosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, March 5, 2022 10:59:07 AM COT
*/

public abstract class GestionUsuariosPOA extends org.omg.PortableServer.Servant
 implements s_gestion_usuarios.sop_corba.GestionUsuariosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("abrirSesion", new java.lang.Integer (0));
    _methods.put ("registrarPersonal", new java.lang.Integer (1));
    _methods.put ("consultarPersonal", new java.lang.Integer (2));
    _methods.put ("listarPersonal", new java.lang.Integer (3));
    _methods.put ("modificarPersonal", new java.lang.Integer (4));
    _methods.put ("eliminarPersonal", new java.lang.Integer (5));
    _methods.put ("registrarPaciente", new java.lang.Integer (6));
    _methods.put ("consultarPaciente", new java.lang.Integer (7));
    _methods.put ("listarPacientes", new java.lang.Integer (8));
    _methods.put ("modificarPaciente", new java.lang.Integer (9));
    _methods.put ("eliminarPaciente", new java.lang.Integer (10));
    _methods.put ("registrarValoracionFisica", new java.lang.Integer (11));
    _methods.put ("consultarValoracionFisica", new java.lang.Integer (12));
    _methods.put ("registrarAsistencia", new java.lang.Integer (13));
    _methods.put ("consultarAsistencia", new java.lang.Integer (14));
    _methods.put ("registrarProgramaFisico", new java.lang.Integer (15));
    _methods.put ("consultarProgramaFisico", new java.lang.Integer (16));
    _methods.put ("registrarCallback", new java.lang.Integer (17));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionUsuarios/abrirSesion
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.CredencialesDTO credenciales = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.CredencialesDTOHelper.read (in);
         int $result = (int)0;
         $result = this.abrirSesion (credenciales);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // sop_corba/GestionUsuarios/registrarPersonal
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO personal = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarPersonal (personal);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba/GestionUsuarios/consultarPersonal
       {
         int id = in.read_long ();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO $result = null;
         $result = this.consultarPersonal (id);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.write (out, $result);
         break;
       }

       case 3:  // sop_corba/GestionUsuarios/listarPersonal
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO $result[] = null;
         $result = this.listarPersonal ();
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonasHelper.write (out, $result);
         break;
       }

       case 4:  // sop_corba/GestionUsuarios/modificarPersonal
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO personal = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.read (in);
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO $result = null;
         $result = this.modificarPersonal (personal);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.write (out, $result);
         break;
       }

       case 5:  // sop_corba/GestionUsuarios/eliminarPersonal
       {
         int id = in.read_long ();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO $result = null;
         $result = this.eliminarPersonal (id);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.write (out, $result);
         break;
       }

       case 6:  // sop_corba/GestionUsuarios/registrarPaciente
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO paciente = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarPaciente (paciente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // sop_corba/GestionUsuarios/consultarPaciente
       {
         int id = in.read_long ();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO $result = null;
         $result = this.consultarPaciente (id);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.write (out, $result);
         break;
       }

       case 8:  // sop_corba/GestionUsuarios/listarPacientes
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO $result[] = null;
         $result = this.listarPacientes ();
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacientesHelper.write (out, $result);
         break;
       }

       case 9:  // sop_corba/GestionUsuarios/modificarPaciente
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO paciente = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.read (in);
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO $result = null;
         $result = this.modificarPaciente (paciente);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.write (out, $result);
         break;
       }

       case 10:  // sop_corba/GestionUsuarios/eliminarPaciente
       {
         int id = in.read_long ();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO $result = null;
         $result = this.eliminarPaciente (id);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTOHelper.write (out, $result);
         break;
       }

       case 11:  // sop_corba/GestionUsuarios/registrarValoracionFisica
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTO valoracion = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarValoracionFisica (valoracion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 12:  // sop_corba/GestionUsuarios/consultarValoracionFisica
       {
         int id = in.read_long ();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTO $result = null;
         $result = this.consultarValoracionFisica (id);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTOHelper.write (out, $result);
         break;
       }

       case 13:  // sop_corba/GestionUsuarios/registrarAsistencia
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTO asistencia = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarAsistencia (asistencia);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 14:  // sop_corba/GestionUsuarios/consultarAsistencia
       {
         int id = in.read_long ();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTO $result[] = null;
         $result = this.consultarAsistencia (id);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciasHelper.write (out, $result);
         break;
       }

       case 15:  // sop_corba/GestionUsuarios/registrarProgramaFisico
       {
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO programa = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarProgramaFisico (programa);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 16:  // sop_corba/GestionUsuarios/consultarProgramaFisico
       {
         int id = in.read_long ();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO $result = null;
         $result = this.consultarProgramaFisico (id);
         out = $rh.createReply();
         s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTOHelper.write (out, $result);
         break;
       }

       case 17:  // sop_corba/GestionUsuarios/registrarCallback
       {
         s_gestion_usuarios.sop_corba.PafCallback callback = s_gestion_usuarios.sop_corba.PafCallbackHelper.read (in);
         this.registrarCallback (callback);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionUsuarios:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionUsuarios _this() 
  {
    return GestionUsuariosHelper.narrow(
    super._this_object());
  }

  public GestionUsuarios _this(org.omg.CORBA.ORB orb) 
  {
    return GestionUsuariosHelper.narrow(
    super._this_object(orb));
  }


} // class GestionUsuariosPOA
