package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionUsuariosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, March 5, 2022 10:59:07 AM COT
*/

public interface GestionUsuariosOperations 
{
  int abrirSesion (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.CredencialesDTO credenciales);
  boolean registrarPersonal (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO personal);
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO consultarPersonal (int id);
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO[] listarPersonal ();
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO modificarPersonal (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO personal);
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PersonalDTO eliminarPersonal (int id);
  boolean registrarPaciente (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO paciente);
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO consultarPaciente (int id);
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO[] listarPacientes ();
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO modificarPaciente (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO paciente);
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.PacienteDTO eliminarPaciente (int id);
  boolean registrarValoracionFisica (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTO valoracion);
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTO consultarValoracionFisica (int id);
  boolean registrarAsistencia (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTO asistencia);
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTO[] consultarAsistencia (int id);
  boolean registrarProgramaFisico (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO programa);
  s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO consultarProgramaFisico (int id);
  void registrarCallback (s_gestion_usuarios.sop_corba.PafCallback callback);
} // interface GestionUsuariosOperations
