package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionUsuarios.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, March 5, 2022 10:59:07 AM COT
*/

public interface GestionUsuarios extends GestionUsuariosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionUsuarios
