package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/PafCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, March 5, 2022 10:59:07 AM COT
*/

public interface PafCallbackOperations 
{
  void notificar (String mensaje);
} // interface PafCallbackOperations
