module sop_corba{

  interface PafCallback;

	interface GestionUsuarios{


		struct PersonalDTO
		{
      string tipoId;
      long id;
	    string nombreCompleto;
      string ocupacion;
      string usuario;
      string clave;
		};

    struct CredencialesDTO
    {
        string usuario;
        string clave;
    };

    struct PacienteDTO
    {
      long id;
      string nombre;
      string facultad;
      string tipoUsuario;
      string fechaIngreso;
      string patologia;
      string usuario;
      string clave;
    };

    struct ValoracionFisicaDTO
    {
      long id;
      long idPaciente;
      string fecha;
      long frecuenciaCardiacaReposo;
      long frecuenciaCardiacaActiva;
      long estatura;
      long brazo;
      long pecho;
      long cintura;
      string estado;
    };

    struct AsistenciaDTO 
    {
      long id;
      long idPaciente;
      string fecha;
      string observacion;
    };

    struct EjercicioDTO
    {
      long id;
      string nombre;
      long repeticiones;
      float peso;
    };

    typedef sequence<EjercicioDTO> Ejercicios;
    typedef sequence<PersonalDTO> Personas;
    typedef sequence<PacienteDTO> Pacientes;
    typedef sequence<AsistenciaDTO> Asistencias;

    struct ProgramaSemanaDTO
    {
      string semana;
      Ejercicios ejercicios;
    };

    typedef sequence<ProgramaSemanaDTO> Semanas;

    struct ProgramaFisicoDTO
    {
      long id;
      long idPaciente;
      string fechaInicio;
      Semanas semanas;
    };

    long abrirSesion(in CredencialesDTO credenciales);
		boolean registrarPersonal(in PersonalDTO paciente);
		PersonalDTO consultarPersonal(in long id);
    Personas listarPersonal();
    boolean registrarPaciente(in PacienteDTO paciente);
    PacienteDTO consultarPaciente(in long id);
    Pacientes listarPacientes();
    boolean registrarValoracionFisica(in ValoracionFisicaDTO valoracion);
    ValoracionFisicaDTO consultarValoracionFisica(in long id);
    boolean registrarAsistencia(in AsistenciaDTO asistencia);
    Asistencias consultarAsistencia(in long id);
    boolean registrarProgramaFisico(in ProgramaFisicoDTO programa);
    ProgramaFisicoDTO consultarProgramaFisico(in long id);
    void registrarCallback(in PafCallback callback);
	};

  interface PafCallback{
    void notificar(in string mensaje);
  };
};
