package personal.sop_corba.GestionUsuariosPackage;


/**
* personal/sop_corba/GestionUsuariosPackage/AsistenciaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, February 26, 2022 12:42:38 AM COT
*/

public final class AsistenciaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int idPaciente = (int)0;
  public String fecha = null;
  public String observacion = null;

  public AsistenciaDTO ()
  {
  } // ctor

  public AsistenciaDTO (int _id, int _idPaciente, String _fecha, String _observacion)
  {
    id = _id;
    idPaciente = _idPaciente;
    fecha = _fecha;
    observacion = _observacion;
  } // ctor

} // class AsistenciaDTO
