package personal.sop_corba.GestionUsuariosPackage;

/**
 * personal/sop_corba/GestionUsuariosPackage/EjercicioDTO.java . Generated by
 * the IDL-to-Java compiler (portable), version "3.2" from usuarios.idl Tuesday,
 * March 1, 2022 2:25:28 PM COT
 */
public final class EjercicioDTO implements org.omg.CORBA.portable.IDLEntity {

    public int id = (int) 0;
    public String nombre = "";
    public int repeticiones = (int) 0;
    public float peso = (float) 0;

    public EjercicioDTO() {
    } // ctor

    public EjercicioDTO(int _id, String _nombre, int _repeticiones, float _peso) {
        id = _id;
        nombre = _nombre;
        repeticiones = _repeticiones;
        peso = _peso;
    } // ctor

    @Override
    public String toString() {
        return "\nId=" + id + "\nNombre=" + nombre + "\nRepeticiones=" + repeticiones + "\nPeso=" + peso;
    }
} // class EjercicioDTO
