package personal.sop_corba.GestionUsuariosPackage;

/**
 * personal/sop_corba/GestionUsuariosPackage/PacienteDTO.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from usuarios.idl Tuesday,
 * March 1, 2022 2:25:28 PM COT
 */
public final class PacienteDTO implements org.omg.CORBA.portable.IDLEntity {

    public int id = (int) 0;
    public String nombre = "";
    public String facultad = "";
    public String tipoUsuario = "";
    public String fechaIngreso = "";
    public String patologia = "";
    public String usuario = "";
    public String clave = "";

    public PacienteDTO() {
    } // ctor

    public PacienteDTO(int _id, String _nombre, String _facultad, String _tipoUsuario, String _fechaIngreso, String _patologia, String _usuario, String _clave) {
        id = _id;
        nombre = _nombre;
        facultad = _facultad;
        tipoUsuario = _tipoUsuario;
        fechaIngreso = _fechaIngreso;
        patologia = _patologia;
        usuario = _usuario;
        clave = _clave;
    } // ctor

} // class PacienteDTO
