package personal.sop_corba.GestionUsuariosPackage;

/**
* personal/sop_corba/GestionUsuariosPackage/ProgramaSemanaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Tuesday, March 1, 2022 2:25:28 PM COT
*/

public final class ProgramaSemanaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public personal.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTO value = null;

  public ProgramaSemanaDTOHolder ()
  {
  }

  public ProgramaSemanaDTOHolder (personal.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = personal.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    personal.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return personal.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTOHelper.type ();
  }

}
