package personal.sop_corba.GestionUsuariosPackage;


/**
* personal/sop_corba/GestionUsuariosPackage/SemanasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Sunday, February 27, 2022 4:47:09 PM COT
*/

public final class SemanasHolder implements org.omg.CORBA.portable.Streamable
{
  public personal.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTO value[] = null;

  public SemanasHolder ()
  {
  }

  public SemanasHolder (personal.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = personal.sop_corba.GestionUsuariosPackage.SemanasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    personal.sop_corba.GestionUsuariosPackage.SemanasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return personal.sop_corba.GestionUsuariosPackage.SemanasHelper.type ();
  }

}
