package personal.sop_corba.GestionUsuariosPackage;

/**
 * personal/sop_corba/GestionUsuariosPackage/ValoracionFisicaDTO.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * usuarios.idl Saturday, February 26, 2022 12:13:45 PM COT
 */
public final class ValoracionFisicaDTO implements org.omg.CORBA.portable.IDLEntity {

    public int id = (int) 0;
    public int idPaciente = (int) 0;
    public String fecha = null;
    public int frecuenciaCardiacaReposo = (int) 0;
    public int frecuenciaCardiacaActiva = (int) 0;
    public int estatura = (int) 0;
    public int brazo = (int) 0;
    public int pecho = (int) 0;
    public int cintura = (int) 0;
    public String estado = null;

    public ValoracionFisicaDTO() {
    } // ctor

    public ValoracionFisicaDTO(int _id, int _idPaciente, String _fecha, int _frecuenciaCardiacaReposo, int _frecuenciaCardiacaActiva, int _estatura, int _brazo, int _pecho, int _cintura, String _estado) {
        id = _id;
        idPaciente = _idPaciente;
        fecha = _fecha;
        frecuenciaCardiacaReposo = _frecuenciaCardiacaReposo;
        frecuenciaCardiacaActiva = _frecuenciaCardiacaActiva;
        estatura = _estatura;
        brazo = _brazo;
        pecho = _pecho;
        cintura = _cintura;
        estado = _estado;
    } // ctor

    public String toCsv() {
        return String.format("%d,%d,%s,%d,%d,%d,%d,%d,%d,%s%n",
                this.id, this.idPaciente, this.fecha, this.frecuenciaCardiacaReposo,
                this.frecuenciaCardiacaActiva, this.estatura, this.brazo, this.pecho,
                this.cintura, this.estado);
    }
    
    public String toPrint() {
        return "Valoracion Fisica.\n" + "Id Paciente: " + idPaciente + " - Fecha: " + fecha 
                + "\nFrecuencia Cardiaca en Reposo: " + frecuenciaCardiacaReposo + " - Frecuencia Cardiaca Activa: " + frecuenciaCardiacaActiva
                + "\nEstatura: " + estatura + " - Brazo: " + brazo + " - Pecho: " + pecho + " - Cintura: " + cintura + " - Estado:" + estado;
    }
} // class ValoracionFisicaDTO
