package personal.sop_corba.GestionUsuariosPackage;


/**
* personal/sop_corba/GestionUsuariosPackage/ValoracionFisicaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, February 26, 2022 12:42:38 AM COT
*/

public final class ValoracionFisicaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int idPaciente = (int)0;
  public String fecha = null;
  public int frecuenciaCardiacaReposo = (int)0;
  public int frecuenciaCardiacaActiva = (int)0;
  public int estatura = (int)0;
  public int brazo = (int)0;
  public int cintura = (int)0;
  public String estado = null;

  public ValoracionFisicaDTO ()
  {
  } // ctor

  public ValoracionFisicaDTO (int _id, int _idPaciente, String _fecha, int _frecuenciaCardiacaReposo, int _frecuenciaCardiacaActiva, int _estatura, int _brazo, int _cintura, String _estado)
  {
    id = _id;
    idPaciente = _idPaciente;
    fecha = _fecha;
    frecuenciaCardiacaReposo = _frecuenciaCardiacaReposo;
    frecuenciaCardiacaActiva = _frecuenciaCardiacaActiva;
    estatura = _estatura;
    brazo = _brazo;
    cintura = _cintura;
    estado = _estado;
  } // ctor

} // class ValoracionFisicaDTO
