package s_notificacion_usuarios.sop_corba;

/**
* s_notificacion_usuarios/sop_corba/GestionNotificacionesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* Saturday, March 5, 2022 10:59:17 AM COT
*/

public final class GestionNotificacionesHolder implements org.omg.CORBA.portable.Streamable
{
  public s_notificacion_usuarios.sop_corba.GestionNotificaciones value = null;

  public GestionNotificacionesHolder ()
  {
  }

  public GestionNotificacionesHolder (s_notificacion_usuarios.sop_corba.GestionNotificaciones initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_notificacion_usuarios.sop_corba.GestionNotificacionesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_notificacion_usuarios.sop_corba.GestionNotificacionesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_notificacion_usuarios.sop_corba.GestionNotificacionesHelper.type ();
  }

}
