package s_notificacion_usuarios.sop_corba;


/**
* s_notificacion_usuarios/sop_corba/GestionNotificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* Saturday, March 5, 2022 10:59:17 AM COT
*/

public interface GestionNotificaciones extends GestionNotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionNotificaciones
