package cliente.presentacion;

import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author yerso
 */
public class GUIMenuSecretaria extends javax.swing.JFrame implements AView {

    /**
     * Creates new form GUIMenuAdmin
     */
    public GUIMenuSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnTipoUsuarioReg = new javax.swing.ButtonGroup();
        tbpPrincipal = new javax.swing.JTabbedPane();
        pnlRegistrarPersonal = new javax.swing.JPanel();
        pnlTituloReg = new javax.swing.JPanel();
        lblTituloRegistrar = new javax.swing.JLabel();
        pnlIdReg = new javax.swing.JPanel();
        lblIdReg = new javax.swing.JLabel();
        txtIdReg = new javax.swing.JTextField();
        pnlNombreReg = new javax.swing.JPanel();
        lblNombreReg = new javax.swing.JLabel();
        txtNombreReg = new javax.swing.JTextField();
        pnlFacultadReg = new javax.swing.JPanel();
        pnlTipoIdRegIzq = new javax.swing.JPanel();
        lblTipoId = new javax.swing.JLabel();
        pnlTipoIdRegDere = new javax.swing.JPanel();
        txtFacultadReg = new javax.swing.JTextField();
        pnlOcupacionReg = new javax.swing.JPanel();
        pnlOcupacionRegIzq = new javax.swing.JPanel();
        lblTipoUsuarioReg = new javax.swing.JLabel();
        pnlOcupacionRegDere = new javax.swing.JPanel();
        rbtnDocenteReg = new javax.swing.JRadioButton();
        rbtnAdministrativoReg = new javax.swing.JRadioButton();
        pnlPatologiaReg = new javax.swing.JPanel();
        lblPatologiaReg = new javax.swing.JLabel();
        txtPatologiaReg = new javax.swing.JTextField();
        pnlUsuarioReg = new javax.swing.JPanel();
        lblUsuarioReg = new javax.swing.JLabel();
        txtUsuarioReg = new javax.swing.JTextField();
        pnlClave = new javax.swing.JPanel();
        lblClaveReg = new javax.swing.JLabel();
        pssClaveReg = new javax.swing.JPasswordField();
        pnlBotonRegistrar = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        lblMensajeErrorReg = new javax.swing.JLabel();
        pnlModificarPersonal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlModificarConsultar = new javax.swing.JPanel();
        lblModificarConsultar = new javax.swing.JLabel();
        txtModificarConsultar = new javax.swing.JTextField();
        btnModificarConsultar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtModificarId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtModificarNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtModificarFacultad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbxModificarTipoUsuario = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtModificarPatologia = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtModificarUsuario = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pssModificarClave = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lblMensajeModificar = new javax.swing.JLabel();
        pnlEliminarPersonal = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblIdEliminar = new javax.swing.JLabel();
        txtIdEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        lblEliminarMensaje = new javax.swing.JLabel();
        pnlConsultarPersonal = new javax.swing.JPanel();
        pnlTituloConsultar = new javax.swing.JPanel();
        lblTituloConsultar = new javax.swing.JLabel();
        pnlConsultaConsultar = new javax.swing.JPanel();
        lblConsultaConsultar = new javax.swing.JLabel();
        txtConsultaConsultar = new javax.swing.JTextField();
        pnlInformacionConsultar = new javax.swing.JPanel();
        lblNombreConsultar = new javax.swing.JLabel();
        lblNombreConsultaRes = new javax.swing.JLabel();
        lblTipoUsuarioConsulta = new javax.swing.JLabel();
        lblTipoUsuarioConsultaRes = new javax.swing.JLabel();
        lblUsuarioConsulta = new javax.swing.JLabel();
        lblUsuarioConsultaRes = new javax.swing.JLabel();
        lblFacultadConsultar = new javax.swing.JLabel();
        lblFacultadConsultarRes = new javax.swing.JLabel();
        pnlSurConsultar = new javax.swing.JPanel();
        pnlMasInfoConsulta = new javax.swing.JPanel();
        lblPatologiaConsultar = new javax.swing.JLabel();
        lblPatologiaConsultarRes = new javax.swing.JLabel();
        lblFechaIngresoConsultar = new javax.swing.JLabel();
        lblFechaIngresoConsultarRes = new javax.swing.JLabel();
        pnlBotonConsultar = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        lblMensajeErrorConsultar = new javax.swing.JLabel();
        pnlListarPersonal = new javax.swing.JPanel();
        pnlNorteListar = new javax.swing.JPanel();
        lblTituloListar = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaPacientes = new javax.swing.JTable();
        lblMensajeErrorListar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Secretaria");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        tbpPrincipal.setPreferredSize(new java.awt.Dimension(500, 700));

        pnlRegistrarPersonal.setLayout(new java.awt.GridLayout(9, 0));

        pnlTituloReg.setLayout(new java.awt.GridLayout(1, 0));

        lblTituloRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRegistrar.setText("Registrar Paciente");
        pnlTituloReg.add(lblTituloRegistrar);

        pnlRegistrarPersonal.add(pnlTituloReg);

        pnlIdReg.setLayout(new java.awt.GridLayout(1, 0));

        lblIdReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdReg.setText("Identificaión");
        pnlIdReg.add(lblIdReg);
        pnlIdReg.add(txtIdReg);

        pnlRegistrarPersonal.add(pnlIdReg);

        pnlNombreReg.setLayout(new java.awt.GridLayout(1, 0));

        lblNombreReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreReg.setText("Nombre Completo");
        pnlNombreReg.add(lblNombreReg);
        pnlNombreReg.add(txtNombreReg);

        pnlRegistrarPersonal.add(pnlNombreReg);

        pnlFacultadReg.setLayout(new java.awt.GridLayout(1, 2));

        pnlTipoIdRegIzq.setLayout(new java.awt.GridLayout(1, 0));

        lblTipoId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoId.setText("Facultad");
        pnlTipoIdRegIzq.add(lblTipoId);

        pnlFacultadReg.add(pnlTipoIdRegIzq);

        pnlTipoIdRegDere.setLayout(new java.awt.GridLayout(1, 0));
        pnlTipoIdRegDere.add(txtFacultadReg);

        pnlFacultadReg.add(pnlTipoIdRegDere);

        pnlRegistrarPersonal.add(pnlFacultadReg);

        pnlOcupacionReg.setLayout(new java.awt.GridLayout(1, 0));

        pnlOcupacionRegIzq.setLayout(new java.awt.GridLayout(1, 0));

        lblTipoUsuarioReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoUsuarioReg.setText("Tipo de Usuario");
        pnlOcupacionRegIzq.add(lblTipoUsuarioReg);

        pnlOcupacionReg.add(pnlOcupacionRegIzq);

        pnlOcupacionRegDere.setLayout(new java.awt.GridLayout(2, 0));

        gbtnTipoUsuarioReg.add(rbtnDocenteReg);
        rbtnDocenteReg.setSelected(true);
        rbtnDocenteReg.setText("Docente");
        pnlOcupacionRegDere.add(rbtnDocenteReg);

        gbtnTipoUsuarioReg.add(rbtnAdministrativoReg);
        rbtnAdministrativoReg.setText("Administrativo");
        pnlOcupacionRegDere.add(rbtnAdministrativoReg);

        pnlOcupacionReg.add(pnlOcupacionRegDere);

        pnlRegistrarPersonal.add(pnlOcupacionReg);

        pnlPatologiaReg.setLayout(new java.awt.GridLayout(1, 0));

        lblPatologiaReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatologiaReg.setText("Patologia del Usuario");
        pnlPatologiaReg.add(lblPatologiaReg);
        pnlPatologiaReg.add(txtPatologiaReg);

        pnlRegistrarPersonal.add(pnlPatologiaReg);

        pnlUsuarioReg.setLayout(new java.awt.GridLayout(1, 0));

        lblUsuarioReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioReg.setText("Usuario");
        pnlUsuarioReg.add(lblUsuarioReg);
        pnlUsuarioReg.add(txtUsuarioReg);

        pnlRegistrarPersonal.add(pnlUsuarioReg);

        pnlClave.setLayout(new java.awt.GridLayout(1, 0));

        lblClaveReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClaveReg.setText("Clave");
        pnlClave.add(lblClaveReg);
        pnlClave.add(pssClaveReg);

        pnlRegistrarPersonal.add(pnlClave);

        pnlBotonRegistrar.setLayout(new java.awt.GridLayout(2, 0));

        btnRegistrar.setText("Registrar");
        pnlBotonRegistrar.add(btnRegistrar);
        pnlBotonRegistrar.add(lblMensajeErrorReg);

        pnlRegistrarPersonal.add(pnlBotonRegistrar);

        tbpPrincipal.addTab("Registar", pnlRegistrarPersonal);

        pnlModificarPersonal.setLayout(new java.awt.GridLayout(11, 0));

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Modificar Paciente");
        pnlModificarPersonal.add(lblTitulo);

        pnlModificarConsultar.setLayout(new java.awt.GridLayout(1, 0));

        lblModificarConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificarConsultar.setText("Consultar Paciente");
        pnlModificarConsultar.add(lblModificarConsultar);
        pnlModificarConsultar.add(txtModificarConsultar);

        btnModificarConsultar.setText("Consultar");
        pnlModificarConsultar.add(btnModificarConsultar);

        pnlModificarPersonal.add(pnlModificarConsultar);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Identificación");
        jPanel1.add(jLabel1);

        txtModificarId.setEnabled(false);
        jPanel1.add(txtModificarId);

        pnlModificarPersonal.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre Completo");
        jPanel2.add(jLabel2);
        jPanel2.add(txtModificarNombre);

        pnlModificarPersonal.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Facultad");
        jPanel3.add(jLabel3);
        jPanel3.add(txtModificarFacultad);

        pnlModificarPersonal.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tipo de Usuario");
        jPanel4.add(jLabel4);

        cbxModificarTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Docente", "Administrativo" }));
        jPanel4.add(cbxModificarTipoUsuario);

        pnlModificarPersonal.add(jPanel4);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Patologia");
        jPanel9.add(jLabel7);
        jPanel9.add(txtModificarPatologia);

        pnlModificarPersonal.add(jPanel9);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuario");
        jPanel5.add(jLabel5);
        jPanel5.add(txtModificarUsuario);

        pnlModificarPersonal.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clave");
        jPanel6.add(jLabel6);
        jPanel6.add(pssModificarClave);

        pnlModificarPersonal.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        jPanel7.add(btnModificar);

        pnlModificarPersonal.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));
        jPanel8.add(lblMensajeModificar);

        pnlModificarPersonal.add(jPanel8);

        tbpPrincipal.addTab("Modificar", pnlModificarPersonal);

        pnlEliminarPersonal.setLayout(new java.awt.GridLayout(5, 0));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Eliminar un paciente");
        pnlEliminarPersonal.add(jLabel8);

        lblIdEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdEliminar.setText("Identificacion");
        pnlEliminarPersonal.add(lblIdEliminar);
        pnlEliminarPersonal.add(txtIdEliminar);

        btnEliminar.setText("Eliminar");
        pnlEliminarPersonal.add(btnEliminar);
        pnlEliminarPersonal.add(lblEliminarMensaje);

        tbpPrincipal.addTab("Eliminar", pnlEliminarPersonal);

        pnlConsultarPersonal.setLayout(new java.awt.GridLayout(3, 0));

        pnlTituloConsultar.setLayout(new java.awt.GridLayout(2, 0));

        lblTituloConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloConsultar.setText("Consultar Personal");
        pnlTituloConsultar.add(lblTituloConsultar);

        pnlConsultaConsultar.setLayout(new java.awt.GridLayout(2, 0));

        lblConsultaConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultaConsultar.setText("Ingrese ID del paciente");
        pnlConsultaConsultar.add(lblConsultaConsultar);

        txtConsultaConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlConsultaConsultar.add(txtConsultaConsultar);

        pnlTituloConsultar.add(pnlConsultaConsultar);

        pnlConsultarPersonal.add(pnlTituloConsultar);

        pnlInformacionConsultar.setLayout(new java.awt.GridLayout(4, 2));

        lblNombreConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreConsultar.setText("Nombre Completo");
        pnlInformacionConsultar.add(lblNombreConsultar);

        lblNombreConsultaRes.setText("-");
        pnlInformacionConsultar.add(lblNombreConsultaRes);

        lblTipoUsuarioConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoUsuarioConsulta.setText("Tipo de Usuario");
        pnlInformacionConsultar.add(lblTipoUsuarioConsulta);

        lblTipoUsuarioConsultaRes.setText("-");
        pnlInformacionConsultar.add(lblTipoUsuarioConsultaRes);

        lblUsuarioConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioConsulta.setText("Usuario");
        pnlInformacionConsultar.add(lblUsuarioConsulta);

        lblUsuarioConsultaRes.setText("-");
        pnlInformacionConsultar.add(lblUsuarioConsultaRes);

        lblFacultadConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacultadConsultar.setText("Facultad");
        pnlInformacionConsultar.add(lblFacultadConsultar);

        lblFacultadConsultarRes.setText("-");
        pnlInformacionConsultar.add(lblFacultadConsultarRes);

        pnlConsultarPersonal.add(pnlInformacionConsultar);

        pnlSurConsultar.setLayout(new java.awt.GridLayout(2, 0));

        pnlMasInfoConsulta.setLayout(new java.awt.GridLayout(2, 0));

        lblPatologiaConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatologiaConsultar.setText("Patologia del Usuario");
        pnlMasInfoConsulta.add(lblPatologiaConsultar);

        lblPatologiaConsultarRes.setText("-");
        pnlMasInfoConsulta.add(lblPatologiaConsultarRes);

        lblFechaIngresoConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaIngresoConsultar.setText("Fecha de Ingreso");
        pnlMasInfoConsulta.add(lblFechaIngresoConsultar);

        lblFechaIngresoConsultarRes.setText("-");
        pnlMasInfoConsulta.add(lblFechaIngresoConsultarRes);

        pnlSurConsultar.add(pnlMasInfoConsulta);

        pnlBotonConsultar.setLayout(new java.awt.GridLayout(2, 0));

        btnConsultar.setText("Consultar");
        pnlBotonConsultar.add(btnConsultar);
        pnlBotonConsultar.add(lblMensajeErrorConsultar);

        pnlSurConsultar.add(pnlBotonConsultar);

        pnlConsultarPersonal.add(pnlSurConsultar);

        tbpPrincipal.addTab("Consultar", pnlConsultarPersonal);

        pnlListarPersonal.setLayout(new java.awt.BorderLayout());

        pnlNorteListar.setLayout(new java.awt.GridLayout(1, 0));

        lblTituloListar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloListar.setText("Listar Pacientes");
        pnlNorteListar.add(lblTituloListar);

        btnListar.setText("Listar");
        pnlNorteListar.add(btnListar);

        pnlListarPersonal.add(pnlNorteListar, java.awt.BorderLayout.NORTH);

        tblListaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre Completo", "Tipo de Usuario", "Facultad", "Usuario", "Patologia", "FechaIngreso"
            }
        ));
        jScrollPane1.setViewportView(tblListaPacientes);

        pnlListarPersonal.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        pnlListarPersonal.add(lblMensajeErrorListar, java.awt.BorderLayout.SOUTH);

        tbpPrincipal.addTab("Listar", pnlListarPersonal);

        getContentPane().add(tbpPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIMenuAdmin().setVisible(true);
//            }
//        });
//    }

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public JButton getBtnListar() {
        return btnListar;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }
    
    public JTextField getTxtNombreReg() {    
        return txtNombreReg;
    }

    public JTextField getTxtIdReg() {
        return txtIdReg;
    }

    public JRadioButton getRbtnDocenteReg() {
        return rbtnDocenteReg;
    }

    public JRadioButton getRbtnAdministrativoReg() {
        return rbtnAdministrativoReg;
    }

    public JTextField getTxtUsuarioReg() {
        return txtUsuarioReg;
    }

    public JTextField getTxtConsultaConsultar() {
        return txtConsultaConsultar;
    }

    public JTextField getTxtFacultadReg() {
        return txtFacultadReg;
    }

    public JTextField getTxtPatologiaReg() {
        return txtPatologiaReg;
    }

    public JPasswordField getPssModificarClave() {
        return pssClaveReg;
    }

    public JLabel getLblMensajeErrorReg() {
        return lblMensajeErrorReg;
    }

    public JLabel getLblFacultadConsultarRes() {
        return lblFacultadConsultarRes;
    }

    public JLabel getLblFechaIngresoConsultarRes() {
        return lblFechaIngresoConsultarRes;
    }

    public JLabel getLblMensajeErrorConsultar() {
        return lblMensajeErrorConsultar;
    }

    public JLabel getLblMensajeErrorListar() {
        return lblMensajeErrorListar;
    }

    public JLabel getLblNombreConsultaRes() {
        return lblNombreConsultaRes;
    }

    public JLabel getLblPatologiaConsultarRes() {
        return lblPatologiaConsultarRes;
    }


    public JLabel getLblUsuarioConsultaRes() {
        return lblUsuarioConsultaRes;
    }
    
    public JTable getTblListaPacientes() {
        return tblListaPacientes;
    }

    public JLabel getLblTipoUsuarioConsultaRes() {
        return lblTipoUsuarioConsultaRes;
    }
    
    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JButton getBtnModificarConsultar() {
        return btnModificarConsultar;
    }

    public JComboBox<String> getCbxModificarTipoUsuario() {
        return cbxModificarTipoUsuario;
    }

    public JPasswordField getPssClaveReg() {
        return pssClaveReg;
    }

    public JTextField getTxtModificarConsultar() {
        return txtModificarConsultar;
    }

    public JTextField getTxtModificarFacultad() {
        return txtModificarFacultad;
    }

    public JTextField getTxtModificarId() {
        return txtModificarId;
    }

    public JTextField getTxtModificarNombre() {
        return txtModificarNombre;
    }

    public JTextField getTxtModificarUsuario() {
        return txtModificarUsuario;
    }

    public JLabel getLblMensajeModificar() {
        return lblMensajeModificar;
    }

    public JTextField getTxtModificarPatologia() {
        return txtModificarPatologia;
    }
    
    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JTextField getTxtIdEliminar() {
        return txtIdEliminar;
    }

    public JLabel getLblEliminarMensaje() {
        return lblEliminarMensaje;
    }
// Variables
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarConsultar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxModificarTipoUsuario;
    private javax.swing.ButtonGroup gbtnTipoUsuarioReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClaveReg;
    private javax.swing.JLabel lblConsultaConsultar;
    private javax.swing.JLabel lblEliminarMensaje;
    private javax.swing.JLabel lblFacultadConsultar;
    private javax.swing.JLabel lblFacultadConsultarRes;
    private javax.swing.JLabel lblFechaIngresoConsultar;
    private javax.swing.JLabel lblFechaIngresoConsultarRes;
    private javax.swing.JLabel lblIdEliminar;
    private javax.swing.JLabel lblIdReg;
    private javax.swing.JLabel lblMensajeErrorConsultar;
    private javax.swing.JLabel lblMensajeErrorListar;
    private javax.swing.JLabel lblMensajeErrorReg;
    private javax.swing.JLabel lblMensajeModificar;
    private javax.swing.JLabel lblModificarConsultar;
    private javax.swing.JLabel lblNombreConsultaRes;
    private javax.swing.JLabel lblNombreConsultar;
    private javax.swing.JLabel lblNombreReg;
    private javax.swing.JLabel lblPatologiaConsultar;
    private javax.swing.JLabel lblPatologiaConsultarRes;
    private javax.swing.JLabel lblPatologiaReg;
    private javax.swing.JLabel lblTipoId;
    private javax.swing.JLabel lblTipoUsuarioConsulta;
    private javax.swing.JLabel lblTipoUsuarioConsultaRes;
    private javax.swing.JLabel lblTipoUsuarioReg;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloConsultar;
    private javax.swing.JLabel lblTituloListar;
    private javax.swing.JLabel lblTituloRegistrar;
    private javax.swing.JLabel lblUsuarioConsulta;
    private javax.swing.JLabel lblUsuarioConsultaRes;
    private javax.swing.JLabel lblUsuarioReg;
    private javax.swing.JPanel pnlBotonConsultar;
    private javax.swing.JPanel pnlBotonRegistrar;
    private javax.swing.JPanel pnlClave;
    private javax.swing.JPanel pnlConsultaConsultar;
    private javax.swing.JPanel pnlConsultarPersonal;
    private javax.swing.JPanel pnlEliminarPersonal;
    private javax.swing.JPanel pnlFacultadReg;
    private javax.swing.JPanel pnlIdReg;
    private javax.swing.JPanel pnlInformacionConsultar;
    private javax.swing.JPanel pnlListarPersonal;
    private javax.swing.JPanel pnlMasInfoConsulta;
    private javax.swing.JPanel pnlModificarConsultar;
    private javax.swing.JPanel pnlModificarPersonal;
    private javax.swing.JPanel pnlNombreReg;
    private javax.swing.JPanel pnlNorteListar;
    private javax.swing.JPanel pnlOcupacionReg;
    private javax.swing.JPanel pnlOcupacionRegDere;
    private javax.swing.JPanel pnlOcupacionRegIzq;
    private javax.swing.JPanel pnlPatologiaReg;
    private javax.swing.JPanel pnlRegistrarPersonal;
    private javax.swing.JPanel pnlSurConsultar;
    private javax.swing.JPanel pnlTipoIdRegDere;
    private javax.swing.JPanel pnlTipoIdRegIzq;
    private javax.swing.JPanel pnlTituloConsultar;
    private javax.swing.JPanel pnlTituloReg;
    private javax.swing.JPanel pnlUsuarioReg;
    private javax.swing.JPasswordField pssClaveReg;
    private javax.swing.JPasswordField pssModificarClave;
    private javax.swing.JRadioButton rbtnAdministrativoReg;
    private javax.swing.JRadioButton rbtnDocenteReg;
    private javax.swing.JTable tblListaPacientes;
    private javax.swing.JTabbedPane tbpPrincipal;
    private javax.swing.JTextField txtConsultaConsultar;
    private javax.swing.JTextField txtFacultadReg;
    private javax.swing.JTextField txtIdEliminar;
    private javax.swing.JTextField txtIdReg;
    private javax.swing.JTextField txtModificarConsultar;
    private javax.swing.JTextField txtModificarFacultad;
    private javax.swing.JTextField txtModificarId;
    private javax.swing.JTextField txtModificarNombre;
    private javax.swing.JTextField txtModificarPatologia;
    private javax.swing.JTextField txtModificarUsuario;
    private javax.swing.JTextField txtNombreReg;
    private javax.swing.JTextField txtPatologiaReg;
    private javax.swing.JTextField txtUsuarioReg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel arg0) {
    }
}
