package s_gestion_usuarios.sop_corba.GestionUsuariosPackage;


/**
* s_gestion_usuarios/sop_corba/GestionUsuariosPackage/AsistenciasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, March 5, 2022 10:59:07 AM COT
*/

public final class AsistenciasHolder implements org.omg.CORBA.portable.Streamable
{
  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTO value[] = null;

  public AsistenciasHolder ()
  {
  }

  public AsistenciasHolder (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciaDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_gestion_usuarios.sop_corba.GestionUsuariosPackage.AsistenciasHelper.type ();
  }

}
