package s_gestion_usuarios.sop_corba.GestionUsuariosPackage;

/**
 * s_gestion_usuarios/sop_corba/GestionUsuariosPackage/AsistenciaDTO.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * usuarios.idl Saturday, March 5, 2022 10:59:07 AM COT
 */
public final class AsistenciaDTO implements org.omg.CORBA.portable.IDLEntity {

    public int id = (int) 0;
    public int idPaciente = (int) 0;
    public String fecha = "";
    public String observacion = "";

    public String toCsv() {
        return String.format("%d,%d,%s,%s%n", this.id, this.idPaciente, this.fecha, this.observacion);
    }

    public String toPrint() {
        return String.format("Id: %d%nId paciente: %d%nFecha: %s%nObservacion: %s%n", this.id, this.idPaciente, this.fecha, this.observacion);
    }

    public AsistenciaDTO() {
    } // ctor

    public AsistenciaDTO(int _id, int _idPaciente, String _fecha, String _observacion) {
        id = _id;
        idPaciente = _idPaciente;
        fecha = _fecha;
        observacion = _observacion;
    } // ctor

} // class AsistenciaDTO
