package s_gestion_usuarios.sop_corba.GestionUsuariosPackage;

/**
 * s_gestion_usuarios/sop_corba/GestionUsuariosPackage/EjercicioDTO.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * usuarios.idl Saturday, March 5, 2022 10:59:07 AM COT
 */
public final class EjercicioDTO implements org.omg.CORBA.portable.IDLEntity {

    public int id = (int) 0;
    public String nombre = "";
    public int repeticiones = (int) 0;
    public float peso = (float) 0;

    @Override
    public String toString() {
        return "\nId=" + id + "\nNombre=" + nombre + "\nRepeticiones=" + repeticiones + "\nPeso=" + peso;
    }

    public EjercicioDTO() {
    } // ctor

    public EjercicioDTO(int _id, String _nombre, int _repeticiones, float _peso) {
        id = _id;
        nombre = _nombre;
        repeticiones = _repeticiones;
        peso = _peso;
    } // ctor

} // class EjercicioDTO
