package s_gestion_usuarios.sop_corba.GestionUsuariosPackage;


/**
* s_gestion_usuarios/sop_corba/GestionUsuariosPackage/EjerciciosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, March 5, 2022 10:59:07 AM COT
*/

public final class EjerciciosHolder implements org.omg.CORBA.portable.Streamable
{
  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTO value[] = null;

  public EjerciciosHolder ()
  {
  }

  public EjerciciosHolder (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjerciciosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjerciciosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjerciciosHelper.type ();
  }

}
