package s_gestion_usuarios.sop_corba.GestionUsuariosPackage;

/**
* s_gestion_usuarios/sop_corba/GestionUsuariosPackage/EjercicioDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, March 5, 2022 10:59:07 AM COT
*/

public final class EjercicioDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTO value = null;

  public EjercicioDTOHolder ()
  {
  }

  public EjercicioDTOHolder (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTOHelper.type ();
  }

}
