package s_gestion_usuarios.sop_corba.GestionUsuariosPackage;

/**
 * s_gestion_usuarios/sop_corba/GestionUsuariosPackage/PersonalDTO.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * usuarios.idl Saturday, March 5, 2022 10:59:07 AM COT
 */
public final class PersonalDTO implements org.omg.CORBA.portable.IDLEntity {

    public String tipoId = "";
    public int id = (int) 0;
    public String nombreCompleto = "";
    public String ocupacion = "";
    public String usuario = "";
    public String clave = "";

    public PersonalDTO() {
    } // ctor

    public PersonalDTO(String _tipoId, int _id, String _nombreCompleto, String _ocupacion, String _usuario, String _clave) {
        tipoId = _tipoId;
        id = _id;
        nombreCompleto = _nombreCompleto;
        ocupacion = _ocupacion;
        usuario = _usuario;
        clave = _clave;
    } // ctor

} // class PersonalDTO
