package s_gestion_usuarios.sop_corba.GestionUsuariosPackage;

import java.util.Arrays;

/**
 * s_gestion_usuarios/sop_corba/GestionUsuariosPackage/ProgramaSemanaDTO.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * usuarios.idl Saturday, March 5, 2022 10:59:07 AM COT
 */
public final class ProgramaSemanaDTO implements org.omg.CORBA.portable.IDLEntity {

    public String semana = "";
    public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTO ejercicios[] = new s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTO[0];

    @Override
    public String toString() {
        return "Semana=" + semana + "\nEjercicios=" + Arrays.toString(ejercicios);
    }

    public ProgramaSemanaDTO() {
    } // ctor

    public ProgramaSemanaDTO(String _semana, s_gestion_usuarios.sop_corba.GestionUsuariosPackage.EjercicioDTO[] _ejercicios) {
        semana = _semana;
        ejercicios = _ejercicios;
    } // ctor

} // class ProgramaSemanaDTO
