package s_gestion_usuarios.sop_corba.GestionUsuariosPackage;

import java.util.Arrays;

/**
 * s_gestion_usuarios/sop_corba/GestionUsuariosPackage/ProgramaFisicoDTO.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * usuarios.idl Saturday, March 5, 2022 10:59:07 AM COT
 */
public final class ProgramaFisicoDTO implements org.omg.CORBA.portable.IDLEntity {

    public int id = (int) 0;
    public int idPaciente = (int) 0;
    public String fechaInicio = "";
    public s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTO semanas[] = new s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTO[0];

    @Override
    public String toString() {
        return "Id=" + id + "\nId Paciente=" + idPaciente + "\nFecha Inicio=" + fechaInicio + "\nSemanas=" + Arrays.toString(semanas);
    }

    public ProgramaFisicoDTO() {
    } // ctor

    public ProgramaFisicoDTO(int _id, int _idPaciente, String _fechaInicio, s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTO[] _semanas) {
        id = _id;
        idPaciente = _idPaciente;
        fechaInicio = _fechaInicio;
        semanas = _semanas;
    } // ctor

} // class ProgramaFisicoDTO
