package s_gestion_usuarios.sop_corba.GestionUsuariosPackage;


/**
* s_gestion_usuarios/sop_corba/GestionUsuariosPackage/ProgramaFisicoDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, March 5, 2022 10:59:07 AM COT
*/

abstract public class ProgramaFisicoDTOHelper
{
  private static String  _id = "IDL:sop_corba/GestionUsuarios/ProgramaFisicoDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "idPaciente",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "fechaInicio",
            _tcOf_members0,
            null);
          _tcOf_members0 = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaSemanaDTOHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.SemanasHelper.id (), "Semanas", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "semanas",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTOHelper.id (), "ProgramaFisicoDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO value = new s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO ();
    value.id = istream.read_long ();
    value.idPaciente = istream.read_long ();
    value.fechaInicio = istream.read_string ();
    value.semanas = s_gestion_usuarios.sop_corba.GestionUsuariosPackage.SemanasHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, s_gestion_usuarios.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO value)
  {
    ostream.write_long (value.id);
    ostream.write_long (value.idPaciente);
    ostream.write_string (value.fechaInicio);
    s_gestion_usuarios.sop_corba.GestionUsuariosPackage.SemanasHelper.write (ostream, value.semanas);
  }

}
