package personal.sop_corba;

/**
* personal/sop_corba/GestionUsuariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Tuesday, March 1, 2022 2:25:28 PM COT
*/

public final class GestionUsuariosHolder implements org.omg.CORBA.portable.Streamable
{
  public personal.sop_corba.GestionUsuarios value = null;

  public GestionUsuariosHolder ()
  {
  }

  public GestionUsuariosHolder (personal.sop_corba.GestionUsuarios initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = personal.sop_corba.GestionUsuariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    personal.sop_corba.GestionUsuariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return personal.sop_corba.GestionUsuariosHelper.type ();
  }

}
