package personal.sop_corba;


/**
* sop_corba/GestionUsuariosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Sunday, February 20, 2022 9:09:21 PM COT
*/

public abstract class GestionUsuariosPOA extends org.omg.PortableServer.Servant
 implements personal.sop_corba.GestionUsuariosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("abrirSesion", new java.lang.Integer (0));
    _methods.put ("registrarPersonal", new java.lang.Integer (1));
    _methods.put ("consultarPersonal", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionUsuarios/abrirSesion
       {
         personal.sop_corba.GestionUsuariosPackage.CredencialesDTO credenciales = personal.sop_corba.GestionUsuariosPackage.CredencialesDTOHelper.read (in);
         int $result = (int)0;
         $result = this.abrirSesion (credenciales);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // sop_corba/GestionUsuarios/registrarPersonal
       {
         personal.sop_corba.GestionUsuariosPackage.PersonalDTO paciente = personal.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarPersonal (paciente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba/GestionUsuarios/consultarPersonal
       {
         int id = in.read_long ();
         personal.sop_corba.GestionUsuariosPackage.PersonalDTO $result = null;
         $result = this.consultarPersonal (id);
         out = $rh.createReply();
         personal.sop_corba.GestionUsuariosPackage.PersonalDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionUsuarios:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionUsuarios _this() 
  {
    return GestionUsuariosHelper.narrow(
    super._this_object());
  }

  public GestionUsuarios _this(org.omg.CORBA.ORB orb) 
  {
    return GestionUsuariosHelper.narrow(
    super._this_object(orb));
  }


} // class GestionUsuariosPOA
