package personal.sop_corba;


/**
* personal/sop_corba/GestionUsuarios.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, February 26, 2022 12:13:45 PM COT
*/

public interface GestionUsuarios extends GestionUsuariosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionUsuarios
