package personal.sop_corba;


/**
* personal/sop_corba/GestionUsuariosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Sunday, February 27, 2022 4:47:09 PM COT
*/

public interface GestionUsuariosOperations 
{
  int abrirSesion (personal.sop_corba.GestionUsuariosPackage.CredencialesDTO credenciales);
  boolean registrarPersonal (personal.sop_corba.GestionUsuariosPackage.PersonalDTO paciente);
  personal.sop_corba.GestionUsuariosPackage.PersonalDTO consultarPersonal (int id);
  personal.sop_corba.GestionUsuariosPackage.PersonalDTO[] listarPersonal ();
  boolean registrarPaciente (personal.sop_corba.GestionUsuariosPackage.PacienteDTO paciente);
  personal.sop_corba.GestionUsuariosPackage.PacienteDTO consultarPaciente (int id);
  personal.sop_corba.GestionUsuariosPackage.PacienteDTO[] listarPacientes ();
  boolean registrarValoracionFisica (personal.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTO valoracion);
  personal.sop_corba.GestionUsuariosPackage.ValoracionFisicaDTO consultarValoracionFisica (int id);
  boolean registrarAsistencia (personal.sop_corba.GestionUsuariosPackage.AsistenciaDTO asistencia);
  personal.sop_corba.GestionUsuariosPackage.AsistenciaDTO[] consultarAsistencia (int id);
  boolean registrarProgramaFisico (personal.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO programa);
  personal.sop_corba.GestionUsuariosPackage.ProgramaFisicoDTO consultarProgramaFisico (int id);
  void registrarCallback (personal.sop_corba.PafCallback callback);
} // interface GestionUsuariosOperations
