package personal.sop_corba;


/**
* sop_corba/GestionUsuariosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Sunday, February 20, 2022 9:09:21 PM COT
*/

public interface GestionUsuariosOperations 
{
  int abrirSesion (personal.sop_corba.GestionUsuariosPackage.CredencialesDTO credenciales);
  boolean registrarPersonal (personal.sop_corba.GestionUsuariosPackage.PersonalDTO paciente);
  personal.sop_corba.GestionUsuariosPackage.PersonalDTO consultarPersonal (int id);
} // interface GestionUsuariosOperations
