package personal.sop_corba;


/**
* personal/sop_corba/PafCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Saturday, February 26, 2022 12:42:38 AM COT
*/

public interface PafCallbackOperations 
{
  void notificar (String mensaje);
} // interface PafCallbackOperations
