package personal.sop_corba;


/**
* personal/sop_corba/PafCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* Tuesday, March 1, 2022 2:25:28 PM COT
*/

public interface PafCallbackOperations 
{
  void notificar (String mensaje);
} // interface PafCallbackOperations
