package notificacion.sop_corba;


/**
* sop_corba/GestionNotificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* Sunday, February 20, 2022 10:47:54 PM COT
*/

public interface GestionNotificaciones extends GestionNotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionNotificaciones
