package notificacion.sop_corba;


/**
* notificacion/sop_corba/GestionNotificacionesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* Saturday, February 26, 2022 11:42:57 AM COT
*/

public abstract class GestionNotificacionesPOA extends org.omg.PortableServer.Servant
 implements notificacion.sop_corba.GestionNotificacionesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("enviarNotificacion", new java.lang.Integer (0));
    _methods.put ("agregarHistorial", new java.lang.Integer (1));
    _methods.put ("agregarAsistencia", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionNotificaciones/enviarNotificacion
       {
         String mensaje = in.read_string ();
         this.enviarNotificacion (mensaje);
         out = $rh.createReply();
         break;
       }

       case 1:  // sop_corba/GestionNotificaciones/agregarHistorial
       {
         int id = in.read_long ();
         String historial = in.read_string ();
         boolean $result = false;
         $result = this.agregarHistorial (id, historial);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba/GestionNotificaciones/agregarAsistencia
       {
         String asistencia = in.read_string ();
         boolean $result = false;
         $result = this.agregarAsistencia (asistencia);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionNotificaciones:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionNotificaciones _this() 
  {
    return GestionNotificacionesHelper.narrow(
    super._this_object());
  }

  public GestionNotificaciones _this(org.omg.CORBA.ORB orb) 
  {
    return GestionNotificacionesHelper.narrow(
    super._this_object(orb));
  }


} // class GestionNotificacionesPOA
