package notificacion.sop_corba;


/**
* notificacion/sop_corba/GestionNotificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* Saturday, February 26, 2022 11:42:57 AM COT
*/

public interface GestionNotificaciones extends GestionNotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionNotificaciones
