package notificacion.sop_corba;

/**
* notificacion/sop_corba/GestionNotificacionesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* Saturday, February 26, 2022 11:42:57 AM COT
*/

public final class GestionNotificacionesHolder implements org.omg.CORBA.portable.Streamable
{
  public notificacion.sop_corba.GestionNotificaciones value = null;

  public GestionNotificacionesHolder ()
  {
  }

  public GestionNotificacionesHolder (notificacion.sop_corba.GestionNotificaciones initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = notificacion.sop_corba.GestionNotificacionesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    notificacion.sop_corba.GestionNotificacionesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return notificacion.sop_corba.GestionNotificacionesHelper.type ();
  }

}
