package notificacion.sop_corba;


/**
* sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* Sunday, February 20, 2022 10:47:54 PM COT
*/

public interface GestionNotificacionesOperations 
{
  void enviarNotificacion (String mensaje);
} // interface GestionNotificacionesOperations
