package notificacion.sop_corba;


/**
* notificacion/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificacion.idl
* Saturday, February 26, 2022 11:42:57 AM COT
*/

public interface GestionNotificacionesOperations 
{
  void enviarNotificacion (String mensaje);
  boolean agregarHistorial (int id, String historial);
  boolean agregarAsistencia (String asistencia);
} // interface GestionNotificacionesOperations
